const quotes: string[] = [
  "Berhenti berjudi adalah langkah pertama menuju kebebasan finansial dan mental.",
  "Judi hanya memberi ilusi kemenangan, sedangkan berhenti memberi kebahagiaan nyata.",
  "Setiap hari tanpa berjudi adalah kemenangan untuk diri sendiri.",
  "Berhenti berjudi adalah bentuk menghargai diri dan masa depan.",
  "Kebahagiaan sejati tidak bisa dibeli dengan taruhan, tapi dengan keputusan bijak.",
  "Melepaskan kebiasaan judi adalah hadiah terbesar yang bisa kamu berikan pada dirimu sendiri.",
  "Tidak ada kemenangan yang sebanding dengan kemenangan melawan kecanduan judi.",
  "Berhenti berjudi adalah investasi terbaik untuk kesehatan mental dan fisik.",
  "Tindakan berhenti berjudi adalah keputusan berani untuk hidup lebih baik.",
  "Setiap hari tanpa berjudi adalah langkah menuju kehidupan yang lebih baik.",
  "Judi hanya memberi kenangan buruk, berhenti memberi peluang baru.",
  "Kemenangan terbesar adalah mengalahkan kecanduan judi.",
  "Berhenti berjudi memberi kamu kekuatan untuk menentukan nasib sendiri.",
  "Hidup tanpa judi adalah hidup dengan kebanggaan dan rasa kontrol.",
  "Keputusan berhenti berjudi adalah keputusan untuk hidup dengan integritas.",
  "Menjauh dari judi memberi ruang untuk kebahagiaan dan kedamaian.",
  "Berhenti berjudi adalah tanda kekuatan dan keberanian diri.",
  "Hidup lebih berharga daripada taruhan, pilihlah untuk berhenti berjudi.",
  "Setiap hari tanpa berjudi adalah pencapaian luar biasa.",
  "Berhenti berjudi membebaskanmu dari belenggu kecanduan dan stres.",
  "Kendalikan hidupmu dengan berhenti berjudi dan temukan kebahagiaan sejati.",
  "Keputusan berhenti berjudi adalah langkah menuju masa depan yang cerah.",
  "Melepaskan judi memberi kesempatan untuk fokus pada hal-hal positif dalam hidup.",
  "Judi mungkin menawarkan janji palsu, tetapi berhenti berjudi menawarkan kebebasan sejati.",
  "Berhenti berjudi adalah cara terbaik untuk merawat diri dan kesehatanmu.",
  "Kebebasan sejati datang dengan memilih untuk berhenti berjudi.",
  "Hidup tanpa judi adalah hidup yang penuh dengan kesempatan dan harapan.",
  "Berhenti berjudi adalah keputusan cerdas untuk masa depan yang lebih baik.",
  "Kebanggaan diri dimulai dari keputusan untuk berhenti berjudi.",
  "Judi tidak pernah memberikan hasil yang baik; berhenti adalah kunci untuk perubahan positif.",
  "Setiap keputusan untuk berhenti berjudi adalah langkah menuju kebahagiaan.",
  "Berhenti berjudi adalah cara untuk menghargai dirimu sendiri dan orang-orang di sekitarmu.",
  "Kesehatan mental yang baik dimulai dengan menghindari judi.",
  "Berhenti berjudi adalah jalan menuju kehidupan yang lebih stabil dan bahagia.",
  "Keputusan berhenti berjudi membuka pintu untuk masa depan yang lebih cerah.",
  "Setiap hari yang kamu lewati tanpa berjudi adalah kemenangan bagi dirimu.",
  "Berhenti berjudi memungkinkanmu untuk mengendalikan hidup dan mencapai tujuan.",
  "Judi mungkin menggoda, tetapi berhenti berjudi adalah langkah menuju kesejahteraan.",
  "Berhenti berjudi adalah keputusan yang membebaskan dari beban emosional dan finansial.",
  "Hidup tanpa judi membawa kedamaian dan kepuasan yang lebih besar.",
  "Keputusan untuk berhenti berjudi adalah keputusan untuk hidup dengan penuh makna.",
  "Berhenti berjudi memberi kamu kesempatan untuk meraih impian dan tujuan hidup.",
  "Setiap langkah menuju berhenti berjudi adalah langkah menuju kebebasan dan kebahagiaan.",
  "Judi tidak akan pernah memberi kebahagiaan; berhenti adalah jalan menuju kehidupan yang lebih baik.",
  "Berhenti berjudi adalah tindakan berani untuk menciptakan masa depan yang lebih baik.",
  "Hidup tanpa judi memberi kamu kesempatan untuk menikmati hidup dengan lebih penuh.",
  "Berhenti berjudi adalah cara terbaik untuk meraih keseimbangan dan ketenangan.",
  "Judi hanya menciptakan ilusi; berhenti berjudi menciptakan kenyataan yang lebih baik.",
  "Keputusan berhenti berjudi adalah keputusan untuk mencintai dirimu sendiri.",
  "Berhenti berjudi membuka kesempatan untuk menemukan kebahagiaan sejati dalam hidup.",
  "Judi mungkin menawarkan kesenangan sementara, tetapi berhenti berjudi memberikan kepuasan jangka panjang.",
  "Berhenti berjudi adalah cara untuk menghilangkan stres dan tekanan dari hidupmu.",
  "Hidup tanpa judi memungkinkanmu untuk membangun masa depan yang lebih stabil.",
  "Keputusan untuk berhenti berjudi adalah langkah menuju hidup yang lebih terencana dan bahagia.",
  "Berhenti berjudi adalah langkah pertama menuju hidup yang bebas dari kecanduan dan masalah finansial.",
  "Setiap hari tanpa berjudi adalah kemenangan dalam perjalanan menuju kehidupan yang lebih baik.",
  "Berhenti berjudi adalah investasi untuk kesehatan mental dan kebahagiaan jangka panjang.",
  "Judi hanya menawarkan ilusi; berhenti berjudi memberikan kenyataan yang lebih baik dan memuaskan.",
  "Keputusan berhenti berjudi adalah keputusan untuk hidup dengan lebih penuh dan bermakna.",
  "Hidup tanpa judi memberi ruang untuk pertumbuhan pribadi dan pencapaian baru.",
  "Berhenti berjudi adalah keputusan yang membawa kedamaian dan keseimbangan dalam hidup.",
  "Setiap keputusan untuk berhenti berjudi adalah langkah menuju masa depan yang lebih cerah.",
  "Berhenti berjudi memungkinkanmu untuk menikmati hidup dengan cara yang lebih sehat dan bahagia.",
  "Judi tidak pernah memberi hasil yang diinginkan; berhenti berjudi memberi kesempatan baru.",
  "Berhenti berjudi adalah cara terbaik untuk mengatasi stres dan mencapai kesejahteraan.",
  "Hidup tanpa judi memungkinkanmu untuk fokus pada hal-hal yang benar-benar penting dalam hidup.",
  "Keputusan berhenti berjudi adalah langkah menuju kebebasan dari belenggu kecanduan.",
  "Berhenti berjudi adalah keputusan yang membuka pintu untuk kesempatan baru dan kehidupan yang lebih baik.",
  "Setiap hari tanpa berjudi adalah kemenangan atas kecanduan dan stres.",
  "Berhenti berjudi adalah langkah berani menuju kesehatan mental dan kebahagiaan.",
  "Judi hanya menawarkan kerugian; berhenti berjudi memberikan kesempatan untuk meraih sukses sejati.",
  "Berhenti berjudi adalah keputusan untuk hidup dengan lebih banyak kendali dan kebanggaan.",
  "Hidup tanpa judi memberi ruang untuk kebahagiaan dan pencapaian yang lebih bermakna.",
  "Keputusan berhenti berjudi adalah langkah menuju kehidupan yang lebih stabil dan memuaskan.",
  "Berhenti berjudi memungkinkanmu untuk menikmati hidup dengan cara yang lebih positif dan produktif.",
  "Judi mungkin menawarkan kesenangan sementara, tetapi berhenti berjudi memberikan kepuasan jangka panjang.",
  "Berhenti berjudi adalah investasi terbaik untuk kesehatan dan kebahagiaan jangka panjang.",
  "Setiap hari tanpa berjudi adalah langkah menuju kehidupan yang lebih sehat dan bahagia.",
  "Berhenti berjudi adalah bentuk investasi terbaik untuk masa depan yang lebih baik.",
  "Judi tidak akan pernah memberi kebahagiaan sejati; berhenti berjudi memberi kesempatan untuk kehidupan yang lebih baik.",
  "Keputusan untuk berhenti berjudi adalah keputusan untuk mencintai dan menghargai diri sendiri.",
  "Berhenti berjudi membuka pintu untuk peluang baru dan pencapaian yang lebih besar.",
  "Hidup tanpa judi membawa kedamaian, kebahagiaan, dan kepuasan yang lebih besar.",
  "Berhenti berjudi adalah langkah pertama menuju masa depan yang lebih cerah dan penuh harapan.",
  "Setiap hari yang kamu lewati tanpa berjudi adalah pencapaian luar biasa dalam perjalanan menuju kehidupan yang lebih baik.",
  "Keputusan berhenti berjudi adalah keputusan untuk hidup dengan lebih banyak kendali dan kepuasan.",
  "Berhenti berjudi memberi kamu kesempatan untuk meraih tujuan dan impian hidup dengan lebih baik.",
  "Judi hanya menciptakan ilusi kemenangan; berhenti berjudi memberikan kenyataan yang lebih memuaskan.",
  "Berhenti berjudi adalah keputusan berani untuk hidup dengan lebih banyak kebanggaan dan rasa kontrol.",
  "Hidup tanpa judi memungkinkanmu untuk membangun masa depan yang lebih stabil dan bahagia.",
  "Keputusan untuk berhenti berjudi adalah langkah menuju kesehatan mental dan emosional yang lebih baik.",
  "Berhenti berjudi adalah langkah berani untuk mengatasi kecanduan dan mencapai kebahagiaan sejati.",
  "Judi mungkin menawarkan kesenangan sementara, tetapi berhenti berjudi memberikan kebahagiaan yang lebih dalam dan tahan lama.",
  "Berhenti berjudi adalah keputusan untuk menciptakan kehidupan yang lebih positif dan penuh makna.",
  "Setiap hari tanpa berjudi adalah langkah menuju kehidupan yang lebih sehat dan bahagia.",
  "Berhenti berjudi memungkinkanmu untuk fokus pada hal-hal yang benar-benar penting dalam hidup.",
  "Hidup tanpa judi adalah hidup dengan lebih banyak kesempatan dan harapan.",
  "Berhenti berjudi adalah bentuk investasi terbaik untuk masa depan yang lebih cerah dan penuh kebahagiaan.",
  "Keputusan berhenti berjudi membuka pintu untuk pencapaian yang lebih besar dan kehidupan yang lebih memuaskan.",
  "Berhenti berjudi adalah langkah pertama menuju kesehatan mental, emosional, dan finansial yang lebih baik.",
  "Judi mungkin menawarkan keuntungan sementara, tetapi berhenti berjudi memberikan kemenangan sejati dalam hidup.",
  "Berhenti berjudi memberi kamu kesempatan untuk menikmati hidup dengan cara yang lebih penuh dan bermakna.",
  "Hidup tanpa judi adalah langkah menuju kebebasan, kedamaian, dan kebahagiaan sejati.",
  "Keputusan untuk berhenti berjudi adalah keputusan untuk menciptakan masa depan yang lebih baik dan lebih bahagia.",
  "Berhenti berjudi adalah bentuk investasi terbaik untuk kesejahteraan dan kebahagiaan jangka panjang.",
  "Setiap hari yang kamu lewati tanpa berjudi adalah langkah menuju kehidupan yang lebih sehat dan bahagia.",
  "Berhenti berjudi adalah keputusan untuk hidup dengan lebih banyak kendali, kebanggaan, dan kepuasan.",
  "Hidup tanpa judi memungkinkanmu untuk mencapai tujuan hidup dengan lebih baik dan lebih memuaskan.",
  "Keputusan berhenti berjudi adalah langkah menuju masa depan yang lebih cerah dan penuh harapan.",
  "Berhenti berjudi adalah bentuk penghargaan terbaik untuk diri sendiri dan masa depanmu.",
  "Judi hanya menawarkan kesenangan sementara; berhenti berjudi memberikan kebahagiaan yang lebih dalam dan tahan lama.",
  "Berhenti berjudi adalah keputusan untuk hidup dengan lebih banyak makna dan kepuasan.",
  "Hidup tanpa judi membuka kesempatan untuk mencapai potensi penuh dan meraih impianmu.",
  "Setiap langkah menuju berhenti berjudi adalah langkah menuju kehidupan yang lebih sehat dan bahagia.",
  "Berhenti berjudi adalah bentuk investasi terbaik untuk kesehatan mental, emosional, dan finansialmu.",
  "Judi tidak pernah memberi hasil yang baik; berhenti berjudi memberikan kesempatan untuk kehidupan yang lebih baik.",
  "Keputusan untuk berhenti berjudi adalah keputusan untuk hidup dengan lebih banyak kendali dan kepuasan.",
  "Berhenti berjudi memungkinkanmu untuk meraih kebahagiaan sejati dan mencapai tujuan hidup dengan lebih baik.",
  "Hidup tanpa judi membawa kedamaian dan kepuasan yang lebih besar dalam hidupmu.",
  "Berhenti berjudi adalah keputusan untuk menciptakan masa depan yang lebih cerah dan lebih memuaskan.",
  "Setiap hari tanpa berjudi adalah kemenangan dalam perjalanan menuju kehidupan yang lebih sehat dan bahagia.",
  "Berhenti berjudi adalah bentuk penghargaan terbaik untuk diri sendiri dan masa depanmu.",
  "Judi mungkin menawarkan kesenangan sementara, tetapi berhenti berjudi memberikan kebahagiaan dan kepuasan jangka panjang.",
  "Berhenti berjudi adalah keputusan yang membuka pintu untuk peluang baru dan pencapaian yang lebih besar.",
  "Hidup tanpa judi memungkinkanmu untuk menikmati hidup dengan cara yang lebih positif dan produktif.",
  "Keputusan berhenti berjudi adalah langkah menuju kehidupan yang lebih terencana dan bahagia.",
  "Berhenti berjudi adalah investasi terbaik untuk kesehatan mental dan kebahagiaan jangka panjang.",
  "Setiap hari yang kamu lewati tanpa berjudi adalah langkah menuju kehidupan yang lebih baik dan lebih memuaskan.",
  "Berhenti berjudi adalah bentuk investasi terbaik untuk masa depan yang lebih cerah dan penuh harapan.",
  "Judi mungkin menawarkan kenikmatan sementara, tetapi berhenti berjudi memberikan kebahagiaan yang lebih dalam dan memuaskan.",
  "Berhenti berjudi adalah langkah pertama menuju kehidupan yang bebas dari kecanduan dan masalah finansial.",
  "Hidup tanpa judi membawa kedamaian, kebahagiaan, dan kepuasan yang lebih besar dalam hidupmu.",
  "Keputusan berhenti berjudi membuka pintu untuk peluang baru dan pencapaian yang lebih besar.",
  "Berhenti berjudi memungkinkanmu untuk fokus pada hal-hal yang benar-benar penting dalam hidup.",
  "Judi mungkin menawarkan kesenangan sementara, tetapi berhenti berjudi memberikan kebahagiaan yang lebih mendalam dan memuaskan.",
  "Berhenti berjudi adalah keputusan untuk hidup dengan lebih banyak kendali, kebanggaan, dan kepuasan.",
  "Hidup tanpa judi memberi ruang untuk pertumbuhan pribadi dan pencapaian baru.",
  "Keputusan untuk berhenti berjudi adalah langkah menuju masa depan yang lebih cerah dan penuh kebahagiaan.",
  "Berhenti berjudi adalah bentuk penghargaan terbaik untuk kesehatan mental dan emosionalmu.",
  "Setiap hari tanpa berjudi adalah pencapaian luar biasa dalam perjalanan menuju kehidupan yang lebih baik dan lebih bahagia.",
];

function getRandomQuote(): string {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  return quotes[randomIndex];
}

export default getRandomQuote;
